### ISSUE TITLE
イベント情報提供用Issue

### ISSUE THREAD

**Issue by 10mocy** [nectarition/Quince#4]
Issueでのイベント情報募集は終了しました。

情報提供はこちらのフォームからお願いします。
https://admin.vo.nrsy.jp/

**Comment by kirisame1777** [comment]
- イベント名: ずんスタ★バザールinパシフィックホテル白石Ⅱ
- ジャンル: 東北三姉妹+ずんだもんオンリー
- 開催日: 3/16
- 会場名: パシフィックホテル白石1F　及び　壽丸屋敷
- 備考: 2会場に分けての開催
- WebサイトのURL: https://fuboh.jp/zunko/bazaar_hotel2/
- 運営者名: パシフィックホテル白石　共催　東北ずん子スタンプラリー実行委員会

**Comment by kirisame1777** [comment]
- イベント名:第3回 ついなちゃんドゥルル祭 
- ジャンル: ついなちゃんオンリー
- 開催日: 6/9
- 会場名: 小江戸蔵里 川越市産業観光館 会議室
- 備考: 川越キャラクターベース9内
- WebサイトのURL: https://yukoduka.wixsite.com/kawagoe-cb9-tuina
- 運営者名: ついなちゃんドゥルル祭 事務局

**Comment by kirisame1777** [comment]
- イベント名: 声音文脈
- ジャンル: トーク系ソフトキャラクター関連楽曲中心DJクラブイベント
- 開催日: 5/4
- 会場名: 秋葉原雷神 3F
- 備考: 声音の宴 3次会の翌日
- WebサイトのURL: https://twitter.com/Koeoto_Bunmyaku
- 運営者名: 声音文脈

**Comment by kirisame1777** [comment]
- イベント名: きずなフリークス
- ジャンル: 紲星あかりオンリー
- 開催日: 11/10
- 会場名: 大田区産業プラザPIO
- 備考: コトノハーズフェスタ8と併催　イベント名は正式に出ていないと思われる（開催告知はされている）
- WebサイトのURL: https://kizuna-freaks.com/
- 運営者名: きずなフリークス準備会

**Comment by kirisame1777** [comment]
- イベント名: ゆかりコレクト
- ジャンル: 結月ゆかりオンリー
- 開催日: 11/10
- 会場名: 大田区産業プラザPIO
- 備考: コトノハーズフェスタ8と併催　イベント名は正式に出ていないと思われる（開催告知はされている）
- WebサイトのURL: https://yukari-collect.com/
- 運営者名: ゆかりコレクト準備会

**Comment by 10mocy** [comment]
@kirisame1777 ご提供ありがとうございます！ 更新しました！

**Comment by hinananoha** [comment]
- イベント名:　青っぽいな
- ジャンル: 「あお」を基調とした”トークソフト”オンリー
- 開催日:　2024/9/22
- 会場名: ホワイトキューブ
- 備考: 一次締切 6/17, 最終〆切 7/22 (ずんパ、ボイボ寮祭も同様）
- WebサイトのURL: http://wtst.net/blue/
- 運営者名: 青っぽいな
- イベントの種類: 同人誌即売会

**Comment by 10mocy** [comment]
@hinananoha ご提供ありがとうございます！ 更新しました！
